#pragma once

#include "strife/math/matrix/matrix.h"
#include "strife/math/matrix/matrix2.h"
#include "strife/math/matrix/matrix2f.h"
#include "strife/math/matrix/matrix2i.h"
#include "strife/math/matrix/matrix3.h"
#include "strife/math/matrix/matrix3f.h"
#include "strife/math/matrix/matrix3i.h"
#include "strife/math/matrix/matrix4.h"
#include "strife/math/matrix/matrix4f.h"
#include "strife/math/matrix/matrix4i.h"

#include "strife/math/vector/vector.h"
#include "strife/math/vector/vector2.h"
#include "strife/math/vector/vector2f.h"
#include "strife/math/vector/vector2i.h"
#include "strife/math/vector/vector3.h"
#include "strife/math/vector/vector3f.h"
#include "strife/math/vector/vector3i.h"
#include "strife/math/vector/vector4.h"
#include "strife/math/vector/vector4f.h"
#include "strife/math/vector/vector4i.h"